apache_remove_default_vhost: true
apache_vhosts_filename: "ssl.conf"

apache_global_vhost_settings: |
    LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
    LogFormat "%h %l %u %t \"%r\" %>s %b" common
    LogFormat "%v: %h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" vcombined
    CustomLog "logs/access_log" vcombined
    
    ServerLimit 32
    StartServers 8
    MaxRequestWorkers 1024
    MinSpareThreads 25
    MaxSpareThreads 75
    ThreadsPerChild 32

    AddOutputFilterByType DEFLATE text/plain
    AddOutputFilterByType DEFLATE text/html
    AddOutputFilterByType DEFLATE text/xml
    AddOutputFilterByType DEFLATE text/css
    AddOutputFilterByType DEFLATE application/xml
    AddOutputFilterByType DEFLATE application/xhtml+xml
    AddOutputFilterByType DEFLATE application/rss+xml
    AddOutputFilterByType DEFLATE application/javascript
    AddOutputFilterByType DEFLATE application/x-javascript

    LoadModule ssl_module modules/mod_ssl.so
    Listen 443
    SSLPassPhraseDialog  builtin
    SSLSessionCache         shmcb:/var/cache/mod_ssl/scache(512000)
    SSLSessionCacheTimeout  300
    Mutex default
    SSLRandomSeed startup file:/dev/urandom  256
    SSLRandomSeed connect builtin
    SSLCryptoDevice builtin
apache_vhosts_template: "../../vars/vhost_template.j2"
apache_certificate_key_file: "/etc/httpd/conf/privkey.pem"
apache_certificate_file: "/etc/httpd/conf/cert.pem"
apache_certificate_chain_file: "/etc/httpd/conf/chain.pem"
non_ssl_parameters: |
    ExpiresActive On
    ExpiresDefault "access plus 6 hours"
    RewriteEngine On
    RewriteCond %{HTTPS} off
    RewriteRule ^.*$ https://%{SERVER_NAME}%{REQUEST_URI} [L,R=301,NE]

apache_vhosts:
  - servername: "thunderbird-settings.thunderbird.net"
    documentroot: "/var/www/html/"
    extra_parameters: |
      ExpiresActive On
      ExpiresDefault "access plus 6 hours"
      WSGIDaemonProcess thunderbird-settings.thunderbird.net processes=2 threads=15 display-name=%{GROUP} python-path=/var/www/kinto
      WSGIProcessGroup thunderbird-settings.thunderbird.net
      WSGIScriptAlias    /     /var/www/kinto/app.wsgi
      SetEnv         KINTO_INI /var/www/config/kinto.ini
      <Directory /home/centos/kinto>
          <Files app.wsgi>
              Require all granted
          </Files>
      </Directory>
