- name: Configure and install Kinto
  hosts: "aws_ec2_kinto_web_{{ prodenv }}"
  remote_user: centos
  become: yes
  vars:
    - kinto_db_url: "{{ lookup('env','KINTO_DB_URL') }}"
    - kinto_hmac_secret: "{{ lookup('env','KINTO_HMAC_SECRET') }}"

  tasks:

    - name: Verify production environment is stage or prod
      fail:
        msg: "prodenv is not defined, or is set to something other than stage or prod"
      when: (prodenv is not defined) or ((prodenv != "stage") and (prodenv != "prod"))

    - name: Verify template vars loaded (kinto_db_url)
      fail:
        msg: "kinto_db_url is not defined. You probably need to `source ../files/secrets.sh`"
      when: kinto_db_url is not defined or kinto_db_url == ""

    - name: Verify template vars loaded (kinto_hmac_secret)
      fail:
        msg: "kinto_hmac_secret is not defined. You probably need to `source ../files/secrets.sh`"
      when: kinto_hmac_secret is not defined or kinto_hmac_secret == ""

    - name: Install Prerequisites
      dnf:
        name:
          - libffi-devel
          - openssl-devel
          - python3-devel
          - python3-virtualenv
        state: latest

    - name: Install Kinto
      pip:
        virtualenv: /var/www/kinto/.venv
        virtualenv_python: python3
        name:
          # kinto[postgreql] will try to pull psychopg2 which doesn't work
          # anymore, but will pass if psychopg2-binary is already installed
          - psycopg2-binary
          - kinto[postgresql]
          - kinto-changes
        state: latest

    - name: Setup WSGI file
      copy:
        src: "{{ item }}"
        dest: /var/www/kinto
        mode: 0644
      with_items:
        - "../files/app.wsgi"

    - name: Make Config dir
      file: path="/var/www/kinto/config" state=directory

    - name: Setup Kinto config
      template:
        src: ../templates/kinto_config.j2
        dest: /var/www/kinto/config/kinto.ini

