- name: Configure firewall and install Apache2
  hosts: "aws_ec2_kinto_web_{{ prodenv }}"
  remote_user: centos
  become: yes

  pre_tasks:

    - name: Show defined production environment
      debug:
        msg: "prodenv={{ prodenv }}"
      when: prodenv is defined

    - name: Verify production environment is stage or prod
      fail:
        msg: "prodenv is not defined, or is set to something other than stage or prod"
      when: (prodenv is not defined) or ((prodenv != "stage") and (prodenv != "prod"))

    - name: Show which groups this host is in
      debug:
        msg: "{{ group_names }}"

    - name: Verify apache vars loaded
      debug:
        msg: "apache_vhosts={{ apache_vhosts }}"
      when: apache_vhosts is defined 

    - name: Sanitycheck apache vars
      fail:
        msg: "apache_vhosts not defined."
      when: apache_vhosts is not defined or apache_vhosts == "" or apache_vhosts[0]['servername'] == "local.dev"

    - name: firewalld
      dnf:
        name:
          - firewalld
        state: latest

    - name: Enable firewalld
      service: name=firewalld state=started enabled=yes

    - name: Allow httpd to connect to postgres in selinux
      seboolean:
        name: httpd_can_network_connect_db
        persistent: yes
        state: yes

    - name: Make Document Root
      file:
        path: "/var/www/kinto"
        state: directory
        setype: httpd_sys_content_t

    - name: Make httpd dir
      file: path="/etc/httpd/conf/" state=directory

    - name: Remove any SSL config
      file: path="/etc/httpd/conf.d/ssl.conf" state=absent

    - name: install mod_wsgi
      dnf:
        name: python3-mod_wsgi
        state: latest

    - name: Set MPM to event by copying config file,
      copy:
        src: "{{ item }}"
        dest: /etc/httpd/conf.modules.d
        mode: 0644
      with_items:
        - "../../files/00-mpm.conf"

  roles:
    - { role: geerlingguy.apache }

  post_tasks:
    - name: Make sure http port is open.
      firewalld:
        service: "{{ item }}"
        zone:      public
        permanent: yes
        immediate: yes
        state:     enabled
      with_items:
        - http

    - name: Comment out CustomLog.
      replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^[ ]+CustomLog \"logs\/access_log\" combined'
        replace: ''
        backup: no

    - name: Comment out LogFormat.
      replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^[ ]+LogFormat.*$'
        replace: ''
        backup: no

    - name: Reload service httpd, in all cases.
      systemd:
        name: httpd
        state: reloaded
